package fatec.poo.view;

import fatec.poo.control.DaoCliente;
import fatec.poo.control.DaoPedido;
import fatec.poo.control.DaoVendedor;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Cliente;
import fatec.poo.model.Pedido;
import fatec.poo.model.Vendedor;
import javax.swing.JOptionPane;

/**
 *
 * @author leomoraes
 */
public class GuiPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiPedido
     */
    public GuiPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumeroPedido = new javax.swing.JTextField();
        txtDataPedido = new javax.swing.JTextField();
        txtValorPedido = new javax.swing.JTextField();
        txtCpfCliente = new javax.swing.JTextField();
        txtCpfVendedor = new javax.swing.JTextField();
        btnConsultarVendedor = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        lblNomeVendedor = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Número do Pedido");

        jLabel2.setText("Data do Pedido");

        jLabel3.setText("Valor do Pedido");

        jLabel4.setText("CPF Cliente");

        jLabel5.setText("CPF Vendedor");

        txtDataPedido.setEnabled(false);

        txtValorPedido.setEnabled(false);

        txtCpfCliente.setEnabled(false);

        txtCpfVendedor.setEnabled(false);

        btnConsultarVendedor.setText("Consultar");
        btnConsultarVendedor.setEnabled(false);
        btnConsultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendedorActionPerformed(evt);
            }
        });

        btnConsultarCliente.setText("Consultar");
        btnConsultarCliente.setEnabled(false);
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        lblNomeCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblNomeVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultarVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnIncluir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarCliente)
                            .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarVendedor))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       prepCon = new PreparaConexao("",""); //Usuário e senha       
       prepCon.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
       prepCon.setConnectionString("jdbc:ucanaccess://C:\\Users\\leomo\\OneDrive\\Área de Trabalho\\TRABALHO POO 3\\prjPOOLeonardoMoraes\\src\\fatec\\poo\\basededados\\BD_Projeto.accdb" );
       daoPedido = new DaoPedido(prepCon.abrirConexao());
       daoCliente = new DaoCliente(prepCon.abrirConexao());
       daoVendedor = new DaoVendedor(prepCon.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        pedido = null;
        pedido = daoPedido.consultar(txtNumeroPedido.getText());
        
        if(pedido == null){            
            txtNumeroPedido.setEnabled(false);
            txtDataPedido.setEnabled(true);
            txtValorPedido.setEnabled(true);
            txtCpfCliente.setEnabled(true);
            txtCpfVendedor.setEnabled(false);
            lblNomeCliente.setEnabled(true);
            lblNomeVendedor.setEnabled(true);
            txtDataPedido.requestFocus();
            btnConsultarVendedor.setEnabled(false);
            btnConsultarCliente.setEnabled(true);
            btnConsultar.setEnabled(false);
            btnIncluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }else{
            txtDataPedido.setText(pedido.getDataEmissao());
            txtValorPedido.setText(String.valueOf(pedido.getValor()));
            txtCpfCliente.setText(pedido.getCliente().getCpf());
            txtCpfVendedor.setText(pedido.getVendedor().getCpf());
            lblNomeCliente.setText(pedido.getCliente().getNome());
            lblNomeVendedor.setText(pedido.getVendedor().getNome());
                        
            txtNumeroPedido.setEnabled(false);
            txtDataPedido.setEnabled(true);
            txtValorPedido.setEnabled(true);
            txtCpfCliente.setEnabled(false);
            txtCpfVendedor.setEnabled(false);
            lblNomeCliente.setEnabled(false);
            lblNomeVendedor.setEnabled(false);
            txtDataPedido.requestFocus();
            btnConsultarVendedor.setEnabled(false);
            btnConsultarCliente.setEnabled(false);
            btnConsultar.setEnabled(false);
            btnIncluir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            }         
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        pedido = new Pedido(txtNumeroPedido.getText());
        pedido.setDataEmissao(txtDataPedido.getText());
        pedido.setValor(Double.parseDouble(txtValorPedido.getText()));
        pedido.setDataEmissao(txtDataPedido.getText());
        pedido.setCliente(cliente);
        pedido.setVendedor(vendedor);        
        
       
        
        if(pedido.getValor() > cliente.getLimiteDisponivel()){
            JOptionPane.showMessageDialog(this, "Saldo Insuficiente", "NÃO AUTORIZADA", JOptionPane.ERROR_MESSAGE);
                
                txtNumeroPedido.setEnabled(false);
                txtDataPedido.setEnabled(false);
                txtValorPedido.setEnabled(true);
                txtCpfCliente.setEnabled(false);
                txtCpfVendedor.setEnabled(false);
                lblNomeCliente.setEnabled(false);
                lblNomeVendedor.setEnabled(false);
                txtValorPedido.requestFocus();
                btnConsultarVendedor.setEnabled(false);
                btnConsultarCliente.setEnabled(false);
                btnConsultar.setEnabled(false);
                btnIncluir.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
                
            }else{
                cliente.addPedido(pedido);              
                daoPedido.inserir(pedido); 
                cliente.setLimiteDisponivel(cliente.getLimiteDisponivel() - pedido.getValor());
                if(pedido.getCliente().getLimiteDisponivel()<0){
                JOptionPane.showMessageDialog(this, "Saldo Insuficiente", "NÃO AUTORIZADA", JOptionPane.ERROR_MESSAGE);
                txtValorPedido.requestFocus();
                
            }else{
                daoCliente.alterar(cliente);
                        
                txtNumeroPedido.setText(null);
                txtDataPedido.setText(null);
                txtValorPedido.setText(null);
                txtCpfCliente.setText(null);
                txtCpfVendedor.setText(null);
                lblNomeCliente.setText(null);
                lblNomeVendedor.setText(null);
                txtNumeroPedido.setEnabled(true);
                txtDataPedido.setEnabled(false);
                txtValorPedido.setEnabled(false);
                txtCpfCliente.setEnabled(false);
                txtCpfVendedor.setEnabled(false);
                lblNomeCliente.setEnabled(false);
                lblNomeVendedor.setEnabled(false);
                txtNumeroPedido.requestFocus();
                btnConsultarVendedor.setEnabled(false);
                btnConsultarCliente.setEnabled(false);
                btnConsultar.setEnabled(true);
                btnIncluir.setEnabled(false);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
            }
        }
        
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0){ 
            
            pedido.getCliente().setLimiteDisponivel(pedido.getCliente().getLimiteDisponivel() + pedido.getValor());                      
            
            daoCliente.alterar(pedido.getCliente());
            
            pedido.getCliente().removerPedido(pedido);
                        
            daoPedido.excluir(pedido);           
            
        }  
        
        txtNumeroPedido.setText(null);
        txtDataPedido.setText(null);
        txtValorPedido.setText(null);
        txtCpfCliente.setText(null);
        txtCpfVendedor.setText(null);
        lblNomeCliente.setText(null);
        lblNomeVendedor.setText(null);
        txtNumeroPedido.setEnabled(true);
        txtDataPedido.setEnabled(false);
        txtValorPedido.setEnabled(false);
        txtCpfCliente.setEnabled(false);
        txtCpfVendedor.setEnabled(false);
        lblNomeCliente.setEnabled(false);
        lblNomeVendedor.setEnabled(false);
        txtNumeroPedido.requestFocus();
        btnConsultarVendedor.setEnabled(false);
        btnConsultarCliente.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0){        
        pedido.setDataEmissao(txtDataPedido.getText());
        //pedido.setValor(Double.parseDouble(txtValorPedido.getText()));
        
        if(Double.parseDouble(txtValorPedido.getText()) < pedido.getCliente().getLimiteCredito()){
            Double diferenca = pedido.getValor() - Double.parseDouble(txtValorPedido.getText());
            if(diferenca > 0){
                pedido.getCliente().setLimiteDisponivel(pedido.getCliente().getLimiteDisponivel() - diferenca);
            }else{
                pedido.getCliente().setLimiteDisponivel(pedido.getCliente().getLimiteDisponivel() + diferenca);
            }
            if(pedido.getCliente().getLimiteDisponivel()<0){
                JOptionPane.showMessageDialog(this, "Saldo Insuficiente", "NÃO AUTORIZADA", JOptionPane.ERROR_MESSAGE);
                txtValorPedido.requestFocus();                
            }else{
            daoCliente.alterar(pedido.getCliente());
            pedido.setValor(Double.parseDouble(txtValorPedido.getText()));
            daoPedido.alterar(pedido);}        
        } else{
                JOptionPane.showMessageDialog(this, "Saldo Insuficiente", "NÃO AUTORIZADA", JOptionPane.ERROR_MESSAGE);
                txtValorPedido.requestFocus();
            }        
        }
        
        txtDataPedido.setText(null);
        txtValorPedido.setText(null);
        txtCpfCliente.setText(null);
        txtCpfVendedor.setText(null);
        lblNomeCliente.setText(null);
        lblNomeVendedor.setText(null);
        txtNumeroPedido.setEnabled(true);
        txtDataPedido.setEnabled(false);
        txtValorPedido.setEnabled(false);
        txtCpfCliente.setEnabled(false);
        txtCpfVendedor.setEnabled(false);
        lblNomeCliente.setEnabled(false);
        lblNomeVendedor.setEnabled(false);
        txtDataPedido.requestFocus();
        btnConsultarVendedor.setEnabled(false);
        btnConsultarCliente.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        cliente = null;
        cliente = daoCliente.consultar(txtCpfCliente.getText());

        if (cliente == null) {
            lblNomeCliente.setText("Cliente não localizado. Cadastre o cliente primeiro.");
            txtCpfCliente.requestFocus();
        } else {
            lblNomeCliente.setText(cliente.getNome());
            btnConsultarCliente.setEnabled(false);
            btnConsultarVendedor.setEnabled(true);
            txtCpfCliente.setEnabled(false);
            txtCpfVendedor.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnConsultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendedorActionPerformed
        vendedor = null;
        vendedor = daoVendedor.consultar(txtCpfVendedor.getText());

        if (vendedor == null) {
            lblNomeVendedor.setText("Vendedor não localizado. Cadastre o vendedor primeiro.");
            txtCpfVendedor.requestFocus();
        } else {
            lblNomeVendedor.setText(vendedor.getNome());
            btnConsultarVendedor.setEnabled(false);
            txtCpfVendedor.setEnabled(false);
            btnIncluir.setEnabled(true);            
        }
    }//GEN-LAST:event_btnConsultarVendedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarVendedor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtCpfVendedor;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtValorPedido;
    // End of variables declaration//GEN-END:variables
private DaoPedido daoPedido;
private Pedido pedido;
private PreparaConexao prepCon;
private DaoCliente daoCliente;
private Cliente cliente;
private DaoVendedor daoVendedor;
private Vendedor vendedor;
}
